# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(null=True)),
                ('test_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_env_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Template'),
        ),
        migrations.AddField(
            model_name='request',
            name='test_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Test'),
        ),
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Requester'),
        ),
    ]
